### ISSUE TITLE
break up into separate files by component

### ISSUE THREAD

**Issue by benadida** [votingworks/bmd#1]

**Comment by mirmasoodali** [comment]
Should we put components like the header and footer for each page in separate files? And within that, should we make each of the buttons (back, next, review, et al.) as separate files in themselves?

**Comment by benadida** [comment]
I don't think we need header/footer in separate files, I think we'll have a standard wrapper in index.html? But maybe I'm misunderstanding your question. Yes, I'd like each major reusable component to be in its own file. If there's a helper component that isn't used independently, I'm okay with it being in same file as the main component that uses it.

**Comment by beausmith** [comment]
This issue is resolved with #13 and #14.
