### ISSUE TITLE
Double-tap on "Add" button for write-ins causes all sorts of badness

### ISSUE THREAD

**Issue by benadida** [votingworks/bmd#1028]
There appears to be a delay when tapping "Accept" button on the write-in screen, during which the text of the write-in is cleared and the modal disappears after maybe 300-500ms.

If you tap "Accept" again in that delay (requires a quick double-tap on "Accept"), the result is two write-ins added and selected, one with the intended text, one that is empty. This happens even if it's a "vote for 1" question, meaning we break the validity of the answer. Once this happens, it's possible to keep selected candidates and adding more write-ins, as many as you want. Then, if one deletes one of the empty write-ins, it appears that the application crashes and goes blank (though this doesn't happen every time.)

![Screenshot 2020-01-05 at 10.29.29 AM.png](https://zube.io/files/votingworks/a2d4cb73923bafee65751341376612de-screenshot-2020-01-05-at-10-29-29-am.png)

**Comment by eventualbuddha** [comment]
I can't reproduce this. I tried on Safari & Chrome on macOS. I'm using the built-in trackpad, tried with both tap-to-click and normal clicking. Only ever got a single click registered. Tried on this same sample contest (no. 8), which happens to allow up to 4 write-ins.

**Comment by eventualbuddha** [comment]
Just realized this is probably something to do with our tap handling. Will try with a touchscreen.

**Comment by eventualbuddha** [comment]
I was able to reproduce this with a touch-screen. When tapping we get two distinct `touchdown` events. With clicking we get one `click` and one `dblclick`, so the click handler doesn't fire twice.
