### ISSUE TITLE
should we force scrolling through the full list of candidates?

### ISSUE THREAD

**Issue by benadida** [votingworks/bmd#1032]
if there's a question with a lot of candidates (think primary), should we force a full scroll once before choosing?

**Comment by eventualbuddha** [comment]
What led you to thinking this? Is there precedent in other systems?

**Comment by beausmith** [comment]
I'm not sold on this solution to the problem. I think it has some un-obvious UX which will trip up many users. We are also not certain this will be an issue as we have not had an official ballot which required scrolling.

**Comment by beausmith** [comment]
Additionally, why is this listed under P1? Shouldn't it be in the inbox/triage until this is more clearly defined?

**Comment by benadida** [comment]
@beausmith I listed this under P1 as I think the question / debate on what to do is important for the upcoming milestone. This isn't an immediate coding task, it's a feature discussion.

**Comment by benadida** [comment]
After discussions with UX folks, we don't need to do this, we may explore transitions that make the list of candidates clearer.
