### ISSUE TITLE
Printed ballot is incomplete (mac OS)

### ISSUE THREAD

**Issue by davidascher** [votingworks/bmd#113]
See attached pdf.  Only partial list, no barcode.
[VotingWorks Ballot Marking Device.pdf](https://github.com/votingworks/bmd/files/2946801/VotingWorks.Ballot.Marking.Device.pdf)

**Comment by beausmith** [comment]
Thank you for documenting this issue @davidascher. 

This project is currently a work in progress. 

As a solution to this, we considering options to keep printed ballot to one page given a variable number of contests and content.

**Comment by davidascher** [comment]
Not sure what timescale you're thinking of, but at this point I would personally prioritize figuring out why the current DOM doesn't print, rather than forcing a design change.

**Comment by beausmith** [comment]
Yes, true.
