### ISSUE TITLE
First item appears highlighted but not selected on first load

### ISSUE THREAD

**Issue by benadida** [votingworks/bmd#22]
The background of the first option is grey highlighted, as if it were selected, while radio button is not selected. This happens when a question appears. It's particularly jarring when you select the second option, go forward and then back, at which point two options are grey and only one is radio-button-selected.

**Comment by benadida** [comment]
@beausmith this looks like a weird interaction between the auto-focus and styling, but also I don't think the choice should change automatically when you press the down/up arrows, it should more explicit with, say, space bar to select.

**Comment by beausmith** [comment]
Fixed
