### ISSUE TITLE
Number of selections remaining status

### ISSUE THREAD

**Issue by whitneyq** [votingworks/bmd#247]
## Detailed Description of Problem
The vote selection status at the top of the screen could be more useful for both visual and audio voters. It also forces voters into arithmetic to figure out how many left. 

## Context
This is something we worked very hard on in Anywhere Ballot 1.0, at the direction of Kathyn Summers, the low-literacy expert from UBalt we worked with. Denis also commented on this-he'd noticed the two different approaches in other systems. 

The solution suggested below focuses on actions available rather than just reporting status. It also reduces the number of words in most cases. 

## Possible Solution
The solution is a variable message:

On entry to the contest
      **Vote for 4**

After 1 selection, the count-down message appears, and decrements with each selection
       **Vote for 4. You can choose 3 more.**

After 3 selections, the count-down message decrements to its final state
       **Vote for 4. You can choose 1 more.**

After 4 selections, or a completely voted contest, the countdown message disappears.
        **Vote for 4**

Why: because "You can vote for 0 more" is awkward and forces reading. We've tried other constructions, but they are all a bit difficult, end up sounding either too directive or ambiguous - and don't translate well!

Just to be complete, on a vote-for-1 contest the second countdown message never appears, because they voter either has not made a choice or has done so, but in both cases, the message would not appear.

And, this message does not appear on a Yes/No contest for the same reason. 

## Environment
Any

**Comment by beausmith** [comment]
Moving content to duplicate issue: https://github.com/votingworks/bmd/issues/316
