### ISSUE TITLE
Fine-tune how sliders on settings page work for assistive tech users 

### ISSUE THREAD

**Issue by suzannechapman** [votingworks/bmd#252]
Here are a few reactions & suggestions on the setting page from the assistive tech / accessible voting system expert Whitney and I demo'd the interface with. There are likely a few ways we could mitigate these issues so we'd like to discuss before submitting bug/feature requests.

1. The tab order on the sliders wasn't as expected. The current order is minus > setting you're on > plus. The expert said since it's a slider, he'd expect to do the equivalent of sliding. Ie. starting on setting two, it'd be nice to be able to move forward to setting 3 and select it directly. In other words, each setting level could be selectable.
2. It's not visually clear enough that you've reached the top or bottom of the slider. Maybe current setting you're on should have a larger or colored dot and/or the plus/minus could be more obviously grayed out when not active.
3. There may be a bug in the current setup where once you've selected setting 1 or 4, you're no longer able to move anywhere on the page.
4. No need for a "clear selections" option (ok to leave during active development if it's helpful to have)

Thoughts?

**Comment by whitneyq** [comment]
On #1 above: each position on the slider is individually selectable by touch, so inconsistent, esp. because the focus lands on the current selection. 

On #2  comment for visual design/Oxide: The + and - labels were almost indivisible.

**Comment by beausmith** [comment]
Closing as dup of: https://github.com/votingworks/bmd/issues/313
