### ISSUE TITLE
Refine punctuation options on write-in keyboard

### ISSUE THREAD

**Issue by suzannechapman** [votingworks/bmd#264]
## Detailed Description of Problem

In order to keep the write-in candidate keyboard as simple as possible, we should make sure all necessary punctuation is available and omit unnecessary punctuation that are not likely to be needed in a candidate's name. 

The current implementation offers comma, period, and hyphen. 

Our suggestion is to definitely add a single quote/apostrophe because it will be needed for names like O'Brien. 

Also worth considering:
- double quotes for names like “BO” BOGDAN AMBRZEWICZ _but_ this could also be done just using the single quote/apostrophe like 'BO' BOGDAN AMBRZEWICZ.

If we want to make it as minimal as possible, we could just offer period, single quote/apostrophe, and hyphen. But if we want to accommodate more, we could also include a comma and/or double quotes. 

(note, the reason for having comma is for names like "Doogie Howser, M.D." and "Sammy Davis, Jr.")

## Environment

-all

## Suggested Implementation
Add keys for:
- [x] single quote
- [x] double quote

**Comment by beausmith** [comment]
Implemented in `m4-master`
