### ISSUE TITLE
Change CircleCi caching keys from hardcoded to use template variables

### ISSUE THREAD

**Issue by beausmith** [votingworks/bmd#285]
From: https://github.com/votingworks/bmd/pull/281#discussion_r280253110

---

Ideally solution ✨ automagical 🦄 caching. 

There are many things we can use to create a unique key:
- [Keys and Templates](https://circleci.com/docs/2.0/caching/#using-keys-and-templates)
- [Built-in Environment Variables](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables)

My suggestion:
```
key: bmd-cache-{{checksum ".circleci/config.yml"}}-{{ checksum "package.json" }}
```

**Comment by benadida** [comment]
Done exactly with the trick you mentioned.
