### ISSUE TITLE
figure out how to test setInterval in ActivationPage

### ISSUE THREAD

**Issue by benadida** [votingworks/bmd#288]
Specifically the `/card/read` polling.

**Comment by beausmith** [comment]
- What options exist to push data rather than rely on polling?
- Mocking an API in a jest test isn't difficult.

**Comment by benadida** [comment]
pushing could be done via websocket, but I doubt that's going to be easier to test, and websockets have a ton of failure modes that I'd rather not get into just yet. Polling is likely to be most robust.

**Comment by beausmith** [comment]
Implemented in `m4-master`
