### ISSUE TITLE
Write-in Keyboard is Accessible

### ISSUE THREAD

**Issue by beausmith** [votingworks/bmd#311]
## Problems
- keyboard is not in tab index

## Solutions
- **acceptable** - navigate key by key
- **ideal** - Navigate by row > 3-key group > key

**Comment by benadida** [comment]
In general, it looks the keyboard we're using behaves weirdly. Even outside of our React environment, the individual buttons cannot be clicked or focused from JS. See the standalone demo at

https://franciscohodge.com/projects/simple-keyboard/demo-showcase/module-autocorrect/

We may want to consider an alternative, like:

https://dev.to/rakannimer/introducing-react-onscreen-keyboard-36fc

which *can* have its buttons selected and clicked from JS.

**Comment by beausmith** [comment]
Related comments here: https://github.com/votingworks/bmd/issues/312#issuecomment-492749827

**Comment by beausmith** [comment]
Implemented in `m4-master`
