### ISSUE TITLE
Settings Screen "back" button is not obvious

### ISSUE THREAD

**Issue by beausmith** [votingworks/bmd#331]
User feedback suggests that going back is confusing as they wish to go forward with the changes they have made. 

## Potential Solutions
- Move button to more obvious location.
- Change button label to "Save" or other word suggesting forward progress.
- If Settings Page content is not much, consider using a modal.

**Comment by whitneyq** [comment]
What about "Done" 
And putting the button in the middle of the screen below the settings options, similar to the position of the Start button on the opening screen.

**Comment by beausmith** [comment]
Layout in M7 resolves this issue.
