### ISSUE TITLE
Non-Visual Voter Experience

### ISSUE THREAD

**Issue by beausmith** [votingworks/bmd#332]
## Goals
- [x] Goldilocks content: not too much, not too little, skip-able upon voter input.
- [x] Clearly indicate which buttons to press for which actions.
- [x] Instructions should be inviting rather than commanding. 
- [ ] (more to add here from user test notes)

## Open Question
- [ ] Once max votes per contest are selected, does the "navigate forward" action select the next candidate/choice or does it go to the next contest button?

## Blockers
- [x] Input device needed *new input device acquired*

**Comment by beausmith** [comment]
Most of this has been completed in `m4-master`

**Comment by benadida** [comment]
done.
