### ISSUE TITLE
Write-In keyboard is too small.

### ISSUE THREAD

**Issue by beausmith** [votingworks/bmd#333]

**Comment by whitneyq** [comment]
I'd be happy to talk about alpha vs. qwerty layout considerations if you're interested. We did a little research on this for the VVSG work. Two bottom lines:

- People who know keyboards can navigate ALPHA layouts but prefer QWERTY
- People who don't use computers or don't read well prefer ALPHA

Existing systems:
Switch order is alpha in all current systems. 
One existing system has a QWERTY layout, but does switch access in ALPHA order, and confused everyone (except totally blind voters). 
One has a option to switch between the two (I can't remember how this was done, but I think it was a system that required access switches to be activated [boo] so it was tied to that preference option)

Also, Denis Anson has been noodling on how to do keyboard entry a lot, so we had him talk about his ideas in the[ videos](https://docs.google.com/document/d/1EiN0D9FSdgCGnWAX2781qneB4pqI6l0cQtS5twdlXIo/edit#heading=h.nhkfqua13frg)

**Comment by beausmith** [comment]
@whitneyq - As the topic of keyboard layout is separate than making the keyboard larger, I've opened a new issue for the topic of keyboard layout (https://github.com/votingworks/bmd/issues/374) and have moved your comment there. To keep this issue on topic, I will delete the comment here. Please subscribe to that other issue if you wish to follow further activity on it.

**Comment by beausmith** [comment]
Keyboards are bigger in M7.
