### ISSUE TITLE
See More Scroll Buttons: Use centered partial-circle style.

### ISSUE THREAD

**Issue by beausmith** [votingworks/bmd#358]
![image](https://user-images.githubusercontent.com/28444/57170557-99078280-6dc2-11e9-8f97-fc4b5cf94df6.png)

Related: Create option to place "see more" buttons in tab index for YesNoContests #248.

**Comment by whitneyq** [comment]
Be sure to test the shape with the largest text that will be used on this button. They ran into problems with that on VSAP.  A more elliptical or rounded rectangle shape might size better.

**Comment by beausmith** [comment]
Implemented in M7.
