### ISSUE TITLE
XAC sometimes doesn't work until you restart Chrome

### ISSUE THREAD

**Issue by benadida** [votingworks/bmd#373]
On Windows, with XAC, if the BMD app is loaded at all before the XAC is plugged in, the XAC is not detected. Quit Chrome, plug in XAC, start Chrome again, go to BMD app, and it works. In fact, start Chrome, go to any other web site, plug in XAC, then go to BMD, it still works.

It appears to be that if BMD is loaded by Chrome once before the XAC is plugged in, then even a hard reload won't let BMD access the XAC. Only quitting Chrome works.

We know for sure from https://html5gamepad.com/ that this is not an inherent limitation of Chrome+XAC, since that other site is perfectly able to detect the gamepad as it plugs / unplugs. So it must be the gamepad library we're using.

**Comment by whitneyq** [comment]
Ben, Beau
I don't know if this helps, but early on - around April 12 - I was doing a lot of testing with the XAC and was able to plug, replug, etc with no problems. I don't think I quit Chrome in between.

**Comment by beausmith** [comment]
Will reopen if/when using XAC again in future.
