### ISSUE TITLE
clerk and pollworker screens on BMD

### ISSUE THREAD

**Issue by benadida** [votingworks/bmd#391]
BMD should go through three major states:
- [x] unconfigured
- [x] testing mode
- [x] live mode
- election-over mode (we're not implementing this mode for now)

Only the clerk card can take the BMD from one major state to another.

## Configuring the BMD

- [x] BMD provides on-screen instructions to insert clerk card
- [x] Clerk card insert shows Clerk screen
- [x] Clerk screen shows option to "load election"
- [x] Once election loaded, the BMD is now in test mode.

## Testing the BMD

With clerk card inserted, the clerk screen shows option to:
- [x] print automated test decks
- [x] go to live mode

When the clerk card is removed, the BMD is in manual test mode, where it behaves exactly as live mode, only every ballot says "Test Ballot" and the "insert voter card" screen clearly displays TEST MODE.

## Poll Worker Card

Works the same in either test or real mode
- [x] insert card pops up poll worker menu with option:
  - [x] close / open as often as needed. 
    - [x] When toggled print current # of ballots printed

## Going to Live Mode

- [x] Clerk inserts card in a BMD that is in testing mode
- [x] Clerk has option to "Finish Testing and Zero Machine"
- [x] when pressed, counts are zero'd, and machine is put in live mode
- [x] polls are closed by default.

## Live Mode

- [x] In live mode, the election is either open or closed. Poll workers can open/close as often as desired.
- [x] If closed, the BMD displays "polls are currently closed. Insert poll worker card to open elections."
- [x] If open:
  - [x] Screen prompts voter to insert their voter card
  - [x] Vote away
  - [x] Print ballot
  - [x] Return to start screen

## Wrap-Up

- [x] Clerk inserts card in a BMD that is in live mode
- [x] Clerk has option to "reset the machine"
- [x] Once reset, the machine is unconfigured and the polls can no longer be open / closed by a poll worker.

## Algorithm for Test Deck Printing

Either county-wide or precinct-specific.

A test deck for a single ballot style is:

```
def prepare_test_deck(ballot_style):
    number_of_ballots = max(ballot_style.questions.candidates.length
    ballots = []
    for i = 1 .. number_of_ballots:
        ballots[ballots.length] = newBallot = {}
        for question in ballotStyle.questions:
           newBallot[question.id] = question.candidates[i % question.candidates.length]
```

Then:

```
for precinct in precincts:
   for ballot_style in precinct.ballot_styles:
       prepare_test_deck(ballot_style)

**Comment by beausmith** [comment]
This is great. Thanks @mcchilders and @benadida for documenting it.

**Comment by benadida** [comment]
splitting this into #406  #407 #408 #409

**Comment by beausmith** [comment]
Implemented in `m4-master`
