### ISSUE TITLE
After markVoterCardUsed() cast page is displayed before ballot can be printed.

### ISSUE THREAD

**Issue by benadida** [votingworks/bmd#484]

**Comment by beausmith** [comment]
I'm not 100% certain of the problem which this issue is solving, but I think I've solved it with #490.

**Comment by beausmith** [comment]
By lowering the processCard interval, I was able to reproduce this. 

Working on fix where `markVoterCardUsed` stops the polling and reading of card and returns a function to start the polling again which can be called on `afterPrint` event.
