### ISSUE TITLE
Display "Ballot ID" on printed ballot to make it easy to find a specific paper ballot when necessary.

### ISSUE THREAD

**Issue by beausmith** [votingworks/bmd#485]

**Comment by benadida** [comment]
I will follow up to make the call here based on RLA vs. various state rules.

**Comment by benadida** [comment]
for now, let's not print it. Not useful. Reopen later if we need to.

**Comment by beausmith** [comment]
Ballot ID is needed to find a particular ballot in the case that one is not scanned by VxScan.

**Comment by benadida** [comment]
let's think about how we can make sure this doesn't imply that it identifies the voter.
