### ISSUE TITLE
Display "loading" screen when switching screens to both avoid accidental double-click and provide immediate feedback

### ISSUE THREAD

**Issue by beausmith** [votingworks/bmd#486]
Having some type of short "loading" screen appear when switching between screens will help to do two things:
1. Provide immediate feedback that the user tap was registered.
2. Help avoid the double tap which will cause a voter to skip over a contest when both taps are acted upon.

@benadida says: Interesting.

**Comment by benadida** [comment]
agree, let's do something. Let's test a couple of approaches (slides / curtain / etc.)
