### ISSUE TITLE
figure out printing without a dialog

### ISSUE THREAD

**Issue by benadida** [votingworks/bmd#6]
Chrome extension? something else?

**Comment by beausmith** [comment]
Sounds like what we're looking for is Chrome’s `kiosk mode` and the `Disable Print Preview` flag.

## Research
- https://stackoverflow.com/questions/21073959/print-without-confirmation-on-google-chrome
- https://superuser.com/questions/716426/running-latest-chrome-for-windows-in-kiosk-mode
- https://stackoverflow.com/questions/21908/silent-printing-in-a-web-application

**Comment by beausmith** [comment]
Done!
