### ISSUE TITLE
Voice A11y Review

### ISSUE THREAD

**Issue by beausmith** [votingworks/bmd#63]
- [ ] read print modal
- [ ] read review screen
- [ ] all text on starting page is read by voice
- [ ] speak the question on each question page
- [ ] inputs which should not be read are not (eg. QR code input)
- [ ] for contests, ideally checkboxes are not read and only "ABC is selected" or "ABC is not selected" or similar.
- [ ] review write-in candidate experience.

**Comment by benadida** [comment]
addressed in #76 and #77
