### ISSUE TITLE
Settings need to reset to initial settings when voter card is marked as used

### ISSUE THREAD

**Issue by beausmith** [votingworks/bmd#665]

**Comment by eventualbuddha** [comment]
This appears to already work this way:

https://github.com/votingworks/bmd/blob/90ed93b8f1f934a8b7865aa5b507ebc72a5f650f/src/AppRoot.tsx#L424

I was unable to reproduce the issue by observing font size carrying over from one voter to another. Perhaps this was referring to something else? Or maybe the repro steps I tried are wrong? cc @benadida @csm35
