### ISSUE TITLE
race condition when writing to card

### ISSUE THREAD

**Issue by benadida** [votingworks/bmd#722]
when writing to an actual card (which takes 200ms or so), if you tap and untap a candidate quickly, the second action is canceled, likely because of the race condition with the write. Also, a write on every tap is probably too much.

Recommendation: a background timer that writes the vote to the card every 2 seconds or so, only when the ballot has changed. Or maybe on clicking next. Don't block on it, don't make local state depend on it.

**Comment by beausmith** [comment]
Completed in M7.
