### ISSUE TITLE
better approach to reading the whole page with chromevox

### ISSUE THREAD

**Issue by benadida** [votingworks/bmd#78]
clicking on a container div might be wrong, maybe use `tab-index` on the `main`? Think of `aria-live`? And also look into why the pre-selected choice is different on windows: pressing tab starts with the second option.

/cc @beausmith

**Comment by beausmith** [comment]
I the the right approach is to do two things:'

## Page Navigation
Update each "page" component with a `componentDidMount()` trigger to focus on the DOM element we want focused when that "page" loads via `tab-index="-1"` as documented in this article: https://www.sitepoint.com/learning-to-focus/

## In Page elements which change
Use `aria-live` for any in-page elements which will change based upon interactions.

**Comment by benadida** [comment]
addressed in #136
