### ISSUE TITLE
review UUID barcode generation

### ISSUE THREAD

**Issue by benadida** [votingworks/bmd#88]
The barcode we generate (which is currently fixed and fake) should probably be done via a parameter in `election.json`, as some deployments won't need them and will actively not want them.

- [ ] barcode number should be normal text size.

/cc @beausmith for discussion.

**Comment by benadida** [comment]
The barcode should include some reference to the election definition file so ballots for one election don't get scanned for another election.

**Comment by beausmith** [comment]
Closing as we no longer use 1D barcodes.
